# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 534)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("interface/icons/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_program = QtWidgets.QVBoxLayout()
        self.verticalLayout_program.setObjectName("verticalLayout_program")
        self.verticalLayout_thumbnail = QtWidgets.QVBoxLayout()
        self.verticalLayout_thumbnail.setObjectName("verticalLayout_thumbnail")
        self.frame_thumbnail = QtWidgets.QFrame(self.frame_main)
        self.frame_thumbnail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thumbnail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thumbnail.setObjectName("frame_thumbnail")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_thumbnail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_thumbnail_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_thumbnail_main.setObjectName("verticalLayout_thumbnail_main")
        self.qlabel_thumbnail = QtWidgets.QLabel(self.frame_thumbnail)
        self.qlabel_thumbnail.setText("")
        self.qlabel_thumbnail.setObjectName("qlabel_thumbnail")
        self.verticalLayout_thumbnail_main.addWidget(self.qlabel_thumbnail)
        self.verticalLayout_3.addLayout(self.verticalLayout_thumbnail_main)
        self.verticalLayout_thumbnail.addWidget(self.frame_thumbnail)
        self.verticalLayout_program.addLayout(self.verticalLayout_thumbnail)
        self.verticalLayout_url_fetch = QtWidgets.QVBoxLayout()
        self.verticalLayout_url_fetch.setObjectName("verticalLayout_url_fetch")
        self.frame_url_fetch = QtWidgets.QFrame(self.frame_main)
        self.frame_url_fetch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_url_fetch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_url_fetch.setObjectName("frame_url_fetch")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_url_fetch)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_url_fetch_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_url_fetch_main.setObjectName("horizontalLayout_url_fetch_main")
        self.verticalLayout_url = QtWidgets.QVBoxLayout()
        self.verticalLayout_url.setObjectName("verticalLayout_url")
        self.lineEdit_url = QtWidgets.QLineEdit(self.frame_url_fetch)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.verticalLayout_url.addWidget(self.lineEdit_url)
        self.horizontalLayout_url_fetch_main.addLayout(self.verticalLayout_url)
        self.verticalLayout_fetch = QtWidgets.QVBoxLayout()
        self.verticalLayout_fetch.setObjectName("verticalLayout_fetch")
        self.pushButton_fetch = QtWidgets.QPushButton(self.frame_url_fetch)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("interface/icons/fetch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fetch.setIcon(icon1)
        self.pushButton_fetch.setObjectName("pushButton_fetch")
        self.verticalLayout_fetch.addWidget(self.pushButton_fetch)
        self.horizontalLayout_url_fetch_main.addLayout(self.verticalLayout_fetch)
        self.horizontalLayout_url_fetch_main.setStretch(0, 3)
        self.horizontalLayout_url_fetch_main.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_url_fetch_main)
        self.verticalLayout_url_fetch.addWidget(self.frame_url_fetch)
        self.verticalLayout_program.addLayout(self.verticalLayout_url_fetch)
        self.verticalLayout_progress = QtWidgets.QVBoxLayout()
        self.verticalLayout_progress.setObjectName("verticalLayout_progress")
        self.frame_progress = QtWidgets.QFrame(self.frame_main)
        self.frame_progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progress.setObjectName("frame_progress")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_progress)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_progress_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_progress_main.setObjectName("verticalLayout_progress_main")
        self.progressBar = QtWidgets.QProgressBar(self.frame_progress)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_progress_main.addWidget(self.progressBar)
        self.verticalLayout_6.addLayout(self.verticalLayout_progress_main)
        self.verticalLayout_progress.addWidget(self.frame_progress)
        self.verticalLayout_program.addLayout(self.verticalLayout_progress)
        self.verticalLayout_quality_download = QtWidgets.QVBoxLayout()
        self.verticalLayout_quality_download.setObjectName("verticalLayout_quality_download")
        self.frame_quality_download = QtWidgets.QFrame(self.frame_main)
        self.frame_quality_download.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_quality_download.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_quality_download.setObjectName("frame_quality_download")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_quality_download)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_quality_download_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_quality_download_main.setObjectName("horizontalLayout_quality_download_main")
        self.verticalLayout_quality = QtWidgets.QVBoxLayout()
        self.verticalLayout_quality.setObjectName("verticalLayout_quality")
        self.comboBox_quality = QtWidgets.QComboBox(self.frame_quality_download)
        self.comboBox_quality.setEnabled(False)
        self.comboBox_quality.setObjectName("comboBox_quality")
        self.verticalLayout_quality.addWidget(self.comboBox_quality)
        self.horizontalLayout_quality_download_main.addLayout(self.verticalLayout_quality)
        self.horizontalLayout_download = QtWidgets.QHBoxLayout()
        self.horizontalLayout_download.setObjectName("horizontalLayout_download")
        self.pushButton = QtWidgets.QPushButton(self.frame_quality_download)
        self.pushButton.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("interface/icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_download.addWidget(self.pushButton)
        self.horizontalLayout_quality_download_main.addLayout(self.horizontalLayout_download)
        self.verticalLayout_5.addLayout(self.horizontalLayout_quality_download_main)
        self.verticalLayout_quality_download.addWidget(self.frame_quality_download)
        self.verticalLayout_program.addLayout(self.verticalLayout_quality_download)
        self.verticalLayout_program.setStretch(0, 3)
        self.verticalLayout_program.setStretch(1, 1)
        self.verticalLayout_program.setStretch(2, 1)
        self.verticalLayout_program.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_program, 0, 0, 1, 1)
        self.verticalLayout_main.addWidget(self.frame_main)
        self.verticalLayout_2.addLayout(self.verticalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoutubeDownloader"))
        self.lineEdit_url.setPlaceholderText(_translate("MainWindow", "https://www.youtube.com/watch?v=G1IbRujko-A"))
        self.pushButton_fetch.setText(_translate("MainWindow", "FETCH"))
        self.pushButton.setText(_translate("MainWindow", "DOWNLOAD"))
